# Generated by Django 3.2.5 on 2021-07-14 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Recipient', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('Phonenumber', models.IntegerField(max_length=200)),
                ('Email_address', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=200)),
                ('Basic_illness', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '被接種者',
                'verbose_name_plural': '被接種者',
                'db_table': 'recipient',
            },
        ),
    ]
