# Generated by Django 3.2.4 on 2021-07-15 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, verbose_name='会場名')),
                ('capacity', models.IntegerField(default=0, verbose_name='収容人数')),
                ('hidden_flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='非表示フラグ')),
            ],
            options={
                'verbose_name': '会場マスター',
                'verbose_name_plural': '会場マスター',
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0, verbose_name='年齢')),
                ('hidden_flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='非表示フラグ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '接種者マスター',
                'verbose_name_plural': '接種者マスター',
                'db_table': 'recipient',
            },
        ),
    ]
