# Generated by Django 3.2.4 on 2021-07-15 01:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, verbose_name='会場名')),
                ('capacity', models.IntegerField(default=0, verbose_name='収容人数')),
                ('hidden_flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='非表示フラグ')),
            ],
            options={
                'verbose_name': '会場マスター',
                'verbose_name_plural': '会場マスター',
                'db_table': 'venue',
            },
        ),
        migrations.AddField(
            model_name='recipient',
            name='status',
            field=models.CharField(blank=True, choices=[('a', '未接種'), ('b', '1回目接種完了'), ('c', '2回目接種完了'), ('d', '不接種')], default='a', max_length=1, verbose_name='接種状態'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='Address',
            field=models.CharField(max_length=200, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='Basic_illness',
            field=models.CharField(max_length=200, verbose_name='基礎疾患'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='Email_address',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Recipient', primary_key=True, serialize=False, verbose_name='接種番号'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='Phonenumber',
            field=models.IntegerField(max_length=200, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='姓'),
        ),
    ]
